`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 17:56:54 CST (May  5 2021 09:56:54 UTC)

module SobelFilter_Xor_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  XOR2XL g10(.A (in2), .B (in1), .Y (out1));
endmodule


