`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 02:30:24 CST (May  5 2021 18:30:24 UTC)

module SobelFilter_Add_12Sx10U_13S_1(in2, in1, out1);
  input [11:0] in2;
  input [9:0] in1;
  output [12:0] out1;
  wire [11:0] in2;
  wire [9:0] in1;
  wire [12:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_3, add_23_2_n_10,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28,
       add_23_2_n_29, add_23_2_n_30, add_23_2_n_31, add_23_2_n_32;
  wire add_23_2_n_33, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36,
       add_23_2_n_37, add_23_2_n_38, add_23_2_n_39, add_23_2_n_40;
  wire add_23_2_n_41, add_23_2_n_42, add_23_2_n_43, add_23_2_n_44,
       add_23_2_n_45, add_23_2_n_46, add_23_2_n_47, add_23_2_n_48;
  wire add_23_2_n_49, add_23_2_n_50, add_23_2_n_51, add_23_2_n_52,
       add_23_2_n_53, add_23_2_n_54, add_23_2_n_55, add_23_2_n_56;
  wire add_23_2_n_57, add_23_2_n_58, add_23_2_n_59, add_23_2_n_60,
       add_23_2_n_61, add_23_2_n_62, add_23_2_n_63, add_23_2_n_64;
  wire add_23_2_n_65, add_23_2_n_66, add_23_2_n_67, add_23_2_n_68,
       add_23_2_n_69, add_23_2_n_70, add_23_2_n_71, add_23_2_n_72;
  wire add_23_2_n_73, add_23_2_n_74, add_23_2_n_75, add_23_2_n_76,
       add_23_2_n_78, add_23_2_n_79, add_23_2_n_81, add_23_2_n_108;
  wire add_23_2_n_109, add_23_2_n_110, add_23_2_n_118, add_23_2_n_119,
       add_23_2_n_120, add_23_2_n_121, add_23_2_n_123, add_23_2_n_125;
  wire add_23_2_n_126, add_23_2_n_127, add_23_2_n_129, add_23_2_n_130,
       add_23_2_n_133, add_23_2_n_134, add_23_2_n_135, add_23_2_n_136;
  MXI2X1 add_23_2_g263(.A (in2[10]), .B (add_23_2_n_12), .S0
       (add_23_2_n_79), .Y (out1[10]));
  MXI2XL add_23_2_g264(.A (add_23_2_n_48), .B (add_23_2_n_49), .S0
       (add_23_2_n_78), .Y (out1[9]));
  MXI2X1 add_23_2_g265(.A (in2[11]), .B (add_23_2_n_13), .S0
       (add_23_2_n_81), .Y (out1[11]));
  NOR2BX1 add_23_2_g266(.AN (add_23_2_n_60), .B (add_23_2_n_74), .Y
       (add_23_2_n_81));
  NOR2X1 add_23_2_g267(.A (add_23_2_n_64), .B (add_23_2_n_74), .Y
       (out1[12]));
  NOR2X1 add_23_2_g268(.A (add_23_2_n_52), .B (add_23_2_n_76), .Y
       (add_23_2_n_79));
  NOR2BX1 add_23_2_g269(.AN (add_23_2_n_22), .B (add_23_2_n_75), .Y
       (add_23_2_n_78));
  MXI2XL add_23_2_g271(.A (add_23_2_n_46), .B (add_23_2_n_47), .S0
       (add_23_2_n_71), .Y (out1[7]));
  NOR2BX1 add_23_2_g274(.AN (add_23_2_n_45), .B (add_23_2_n_73), .Y
       (add_23_2_n_76));
  NOR2X1 add_23_2_g275(.A (add_23_2_n_31), .B (add_23_2_n_73), .Y
       (add_23_2_n_75));
  NOR2X2 add_23_2_g276(.A (add_23_2_n_58), .B (add_23_2_n_73), .Y
       (add_23_2_n_74));
  NOR2X2 add_23_2_g277(.A (add_23_2_n_62), .B (add_23_2_n_69), .Y
       (add_23_2_n_73));
  NOR2BX1 add_23_2_g279(.AN (add_23_2_n_125), .B (add_23_2_n_70), .Y
       (add_23_2_n_72));
  NOR2X1 add_23_2_g282(.A (add_23_2_n_63), .B (add_23_2_n_68), .Y
       (add_23_2_n_71));
  NOR2X1 add_23_2_g284(.A (add_23_2_n_30), .B (add_23_2_n_133), .Y
       (add_23_2_n_70));
  NOR2X2 add_23_2_g285(.A (add_23_2_n_57), .B (add_23_2_n_66), .Y
       (add_23_2_n_69));
  NOR2X1 add_23_2_g286(.A (add_23_2_n_56), .B (add_23_2_n_133), .Y
       (add_23_2_n_68));
  NOR2BX1 add_23_2_g287(.AN (add_23_2_n_23), .B (add_23_2_n_2), .Y
       (add_23_2_n_67));
  NOR2X4 add_23_2_g289(.A (add_23_2_n_53), .B (add_23_2_n_65), .Y
       (add_23_2_n_66));
  NOR2X4 add_23_2_g291(.A (add_23_2_n_35), .B (add_23_2_n_61), .Y
       (add_23_2_n_65));
  NAND2X1 add_23_2_g292(.A (in2[11]), .B (add_23_2_n_60), .Y
       (add_23_2_n_64));
  OAI21X1 add_23_2_g293(.A0 (add_23_2_n_118), .A1 (add_23_2_n_55), .B0
       (add_23_2_n_19), .Y (add_23_2_n_63));
  OAI21X1 add_23_2_g294(.A0 (add_23_2_n_38), .A1 (add_23_2_n_55), .B0
       (add_23_2_n_54), .Y (add_23_2_n_62));
  NOR2X2 add_23_2_g295(.A (add_23_2_n_1), .B (add_23_2_n_59), .Y
       (add_23_2_n_61));
  NAND2X1 add_23_2_g297(.A (in2[10]), .B (add_23_2_n_52), .Y
       (add_23_2_n_60));
  NOR2X2 add_23_2_g298(.A (add_23_2_n_16), .B (add_23_2_n_26), .Y
       (add_23_2_n_59));
  NAND2X1 add_23_2_g300(.A (in2[10]), .B (add_23_2_n_45), .Y
       (add_23_2_n_58));
  NAND2X1 add_23_2_g301(.A (add_23_2_n_37), .B (add_23_2_n_36), .Y
       (add_23_2_n_57));
  NAND2BX1 add_23_2_g302(.AN (add_23_2_n_121), .B (add_23_2_n_36), .Y
       (add_23_2_n_56));
  NOR2X2 add_23_2_g304(.A (add_23_2_n_34), .B (add_23_2_n_44), .Y
       (add_23_2_n_55));
  AOI2BB1X1 add_23_2_g305(.A0N (add_23_2_n_19), .A1N (add_23_2_n_17),
       .B0 (add_23_2_n_25), .Y (add_23_2_n_54));
  OAI21X2 add_23_2_g306(.A0 (add_23_2_n_23), .A1 (add_23_2_n_21), .B0
       (add_23_2_n_24), .Y (add_23_2_n_53));
  OAI21X1 add_23_2_g307(.A0 (add_23_2_n_22), .A1 (add_23_2_n_18), .B0
       (add_23_2_n_33), .Y (add_23_2_n_52));
  INVX1 add_23_2_g310(.A (add_23_2_n_48), .Y (add_23_2_n_49));
  INVX1 add_23_2_g311(.A (add_23_2_n_46), .Y (add_23_2_n_47));
  NOR2X1 add_23_2_g312(.A (add_23_2_n_28), .B (add_23_2_n_29), .Y
       (add_23_2_n_44));
  NAND2BX1 add_23_2_g313(.AN (add_23_2_n_31), .B (add_23_2_n_22), .Y
       (add_23_2_n_51));
  NAND2BX1 add_23_2_g314(.AN (add_23_2_n_119), .B (add_23_2_n_19), .Y
       (add_23_2_n_50));
  NOR2X1 add_23_2_g315(.A (add_23_2_n_1), .B (add_23_2_n_26), .Y
       (add_23_2_n_43));
  NOR2BX1 add_23_2_g316(.AN (add_23_2_n_33), .B (add_23_2_n_18), .Y
       (add_23_2_n_48));
  NOR2X1 add_23_2_g317(.A (add_23_2_n_25), .B (add_23_2_n_123), .Y
       (add_23_2_n_46));
  NOR2X1 add_23_2_g318(.A (add_23_2_n_18), .B (add_23_2_n_31), .Y
       (add_23_2_n_45));
  INVX1 add_23_2_g323(.A (add_23_2_n_37), .Y (add_23_2_n_38));
  NAND2X2 add_23_2_g326(.A (add_23_2_n_129), .B (add_23_2_n_32), .Y
       (add_23_2_n_35));
  NAND2BX1 add_23_2_g327(.AN (add_23_2_n_30), .B (add_23_2_n_126), .Y
       (add_23_2_n_42));
  NAND2X1 add_23_2_g328(.A (add_23_2_n_23), .B (add_23_2_n_32), .Y
       (add_23_2_n_41));
  NOR2X1 add_23_2_g329(.A (add_23_2_n_34), .B (add_23_2_n_29), .Y
       (add_23_2_n_40));
  NOR2BX1 add_23_2_g330(.AN (add_23_2_n_24), .B (add_23_2_n_130), .Y
       (add_23_2_n_39));
  NOR2X1 add_23_2_g331(.A (add_23_2_n_17), .B (add_23_2_n_27), .Y
       (add_23_2_n_37));
  NOR2X1 add_23_2_g332(.A (add_23_2_n_29), .B (add_23_2_n_30), .Y
       (add_23_2_n_36));
  AND2X1 add_23_2_g334(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_34));
  NAND2X1 add_23_2_g336(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_33));
  NAND2X2 add_23_2_g337(.A (add_23_2_n_14), .B (add_23_2_n_15), .Y
       (add_23_2_n_32));
  NOR2X1 add_23_2_g338(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_31));
  NOR2X1 add_23_2_g339(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_30));
  NOR2X2 add_23_2_g340(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_29));
  NAND2X1 add_23_2_g341(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_28));
  NOR2X1 add_23_2_g342(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_27));
  NOR2X4 add_23_2_g344(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_26));
  AND2X1 add_23_2_g345(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_25));
  NAND2X1 add_23_2_g346(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_24));
  NAND2X2 add_23_2_g347(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_23));
  NAND2X1 add_23_2_g348(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_22));
  NOR2X4 add_23_2_g349(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_21));
  NAND2X1 add_23_2_g350(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_19));
  NOR2X1 add_23_2_g351(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_18));
  NOR2X2 add_23_2_g352(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_17));
  NAND2X8 add_23_2_g353(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_16));
  INVX1 add_23_2_g355(.A (in1[2]), .Y (add_23_2_n_15));
  CLKINVX2 add_23_2_g356(.A (in2[2]), .Y (add_23_2_n_14));
  INVX1 add_23_2_g358(.A (in2[11]), .Y (add_23_2_n_13));
  INVX1 add_23_2_g360(.A (in2[10]), .Y (add_23_2_n_12));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_16), .B (add_23_2_n_43), .Y
       (out1[1]));
  NOR2BX2 add_23_2_g361(.AN (add_23_2_n_55), .B (add_23_2_n_3), .Y
       (add_23_2_n_10));
  CLKXOR2X1 add_23_2_g362(.A (add_23_2_n_51), .B (add_23_2_n_73), .Y
       (out1[8]));
  CLKXOR2X1 add_23_2_g363(.A (add_23_2_n_50), .B (add_23_2_n_10), .Y
       (out1[6]));
  CLKXOR2X1 add_23_2_g364(.A (add_23_2_n_42), .B (add_23_2_n_134), .Y
       (out1[4]));
  CLKXOR2X1 add_23_2_g365(.A (add_23_2_n_41), .B (add_23_2_n_108), .Y
       (out1[2]));
  XNOR2XL add_23_2_g366(.A (add_23_2_n_40), .B (add_23_2_n_72), .Y
       (out1[5]));
  XNOR2X1 add_23_2_g367(.A (add_23_2_n_39), .B (add_23_2_n_67), .Y
       (out1[3]));
  NOR2BX1 add_23_2_g368(.AN (add_23_2_n_36), .B (add_23_2_n_135), .Y
       (add_23_2_n_3));
  NOR2BX1 add_23_2_g369(.AN (add_23_2_n_32), .B (add_23_2_n_109), .Y
       (add_23_2_n_2));
  CLKAND2X6 add_23_2_g370(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g371(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL add_23_2_fopt(.A (add_23_2_n_110), .Y (add_23_2_n_108));
  INVXL add_23_2_fopt372(.A (add_23_2_n_110), .Y (add_23_2_n_109));
  INVXL add_23_2_fopt373(.A (add_23_2_n_61), .Y (add_23_2_n_110));
  INVXL add_23_2_fopt378(.A (add_23_2_n_120), .Y (add_23_2_n_118));
  INVXL add_23_2_fopt379(.A (add_23_2_n_120), .Y (add_23_2_n_119));
  INVXL add_23_2_fopt380(.A (add_23_2_n_121), .Y (add_23_2_n_120));
  BUFX2 add_23_2_fopt381(.A (add_23_2_n_27), .Y (add_23_2_n_121));
  BUFX2 add_23_2_fopt382(.A (add_23_2_n_17), .Y (add_23_2_n_123));
  INVXL add_23_2_fopt383(.A (add_23_2_n_127), .Y (add_23_2_n_125));
  INVXL add_23_2_fopt384(.A (add_23_2_n_127), .Y (add_23_2_n_126));
  INVXL add_23_2_fopt385(.A (add_23_2_n_28), .Y (add_23_2_n_127));
  CLKINVX3 add_23_2_fopt386(.A (add_23_2_n_21), .Y (add_23_2_n_129));
  BUFX2 add_23_2_fopt387(.A (add_23_2_n_21), .Y (add_23_2_n_130));
  CLKINVX1 add_23_2_fopt388(.A (add_23_2_n_136), .Y (add_23_2_n_133));
  INVXL add_23_2_fopt389(.A (add_23_2_n_136), .Y (add_23_2_n_134));
  INVXL add_23_2_fopt390(.A (add_23_2_n_136), .Y (add_23_2_n_135));
  CLKINVX1 add_23_2_fopt391(.A (add_23_2_n_66), .Y (add_23_2_n_136));
endmodule

