`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 02:30:11 CST (May  5 2021 18:30:11 UTC)

module SobelFilter_Add_11Ux10S_13S_1(in2, in1, out1);
  input [10:0] in2;
  input [9:0] in1;
  output [12:0] out1;
  wire [10:0] in2;
  wire [9:0] in1;
  wire [12:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_3, add_23_2_n_12,
       add_23_2_n_14, add_23_2_n_15, add_23_2_n_16, add_23_2_n_17;
  wire add_23_2_n_18, add_23_2_n_19, add_23_2_n_20, add_23_2_n_21,
       add_23_2_n_22, add_23_2_n_23, add_23_2_n_24, add_23_2_n_25;
  wire add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29,
       add_23_2_n_30, add_23_2_n_31, add_23_2_n_32, add_23_2_n_33;
  wire add_23_2_n_34, add_23_2_n_35, add_23_2_n_36, add_23_2_n_37,
       add_23_2_n_38, add_23_2_n_39, add_23_2_n_40, add_23_2_n_41;
  wire add_23_2_n_42, add_23_2_n_43, add_23_2_n_44, add_23_2_n_45,
       add_23_2_n_46, add_23_2_n_47, add_23_2_n_48, add_23_2_n_49;
  wire add_23_2_n_50, add_23_2_n_51, add_23_2_n_52, add_23_2_n_53,
       add_23_2_n_54, add_23_2_n_55, add_23_2_n_56, add_23_2_n_57;
  wire add_23_2_n_58, add_23_2_n_59, add_23_2_n_60, add_23_2_n_61,
       add_23_2_n_62, add_23_2_n_63, add_23_2_n_64, add_23_2_n_65;
  wire add_23_2_n_66, add_23_2_n_67, add_23_2_n_68, add_23_2_n_69,
       add_23_2_n_70, add_23_2_n_71, add_23_2_n_72, add_23_2_n_73;
  wire add_23_2_n_74, add_23_2_n_75, add_23_2_n_76, add_23_2_n_77,
       add_23_2_n_78, add_23_2_n_79, add_23_2_n_80, add_23_2_n_82;
  wire add_23_2_n_83, add_23_2_n_84, add_23_2_n_109, add_23_2_n_112,
       add_23_2_n_113, add_23_2_n_114, add_23_2_n_116, add_23_2_n_117;
  wire add_23_2_n_118;
  MXI2XL add_23_2_g268(.A (add_23_2_n_52), .B (add_23_2_n_53), .S0
       (add_23_2_n_82), .Y (out1[9]));
  MXI2X1 add_23_2_g269(.A (in1[9]), .B (add_23_2_n_14), .S0
       (add_23_2_n_84), .Y (out1[11]));
  NOR2X1 add_23_2_g270(.A (add_23_2_n_68), .B (add_23_2_n_78), .Y
       (add_23_2_n_84));
  NOR2X2 add_23_2_g271(.A (add_23_2_n_58), .B (add_23_2_n_80), .Y
       (add_23_2_n_83));
  NOR2BX1 add_23_2_g272(.AN (add_23_2_n_21), .B (add_23_2_n_79), .Y
       (add_23_2_n_82));
  NOR2X1 add_23_2_g273(.A (add_23_2_n_67), .B (add_23_2_n_109), .Y
       (out1[12]));
  NOR2BX2 add_23_2_g278(.AN (add_23_2_n_48), .B (add_23_2_n_77), .Y
       (add_23_2_n_80));
  NOR2X1 add_23_2_g279(.A (add_23_2_n_18), .B (add_23_2_n_77), .Y
       (add_23_2_n_79));
  NOR2X1 add_23_2_g280(.A (add_23_2_n_61), .B (add_23_2_n_77), .Y
       (add_23_2_n_78));
  NOR2X4 add_23_2_g281(.A (add_23_2_n_65), .B (add_23_2_n_73), .Y
       (add_23_2_n_77));
  NOR2BX1 add_23_2_g283(.AN (add_23_2_n_30), .B (add_23_2_n_74), .Y
       (add_23_2_n_76));
  NOR2X1 add_23_2_g286(.A (add_23_2_n_66), .B (add_23_2_n_72), .Y
       (add_23_2_n_75));
  NOR2X1 add_23_2_g288(.A (add_23_2_n_35), .B (add_23_2_n_70), .Y
       (add_23_2_n_74));
  NOR2X4 add_23_2_g289(.A (add_23_2_n_60), .B (add_23_2_n_70), .Y
       (add_23_2_n_73));
  NOR2X1 add_23_2_g290(.A (add_23_2_n_59), .B (add_23_2_n_70), .Y
       (add_23_2_n_72));
  NOR2BX1 add_23_2_g291(.AN (add_23_2_n_19), .B (add_23_2_n_2), .Y
       (add_23_2_n_71));
  NOR2X6 add_23_2_g293(.A (add_23_2_n_55), .B (add_23_2_n_69), .Y
       (add_23_2_n_70));
  NOR2X4 add_23_2_g295(.A (add_23_2_n_46), .B (add_23_2_n_64), .Y
       (add_23_2_n_69));
  NAND2X1 add_23_2_g296(.A (add_23_2_n_31), .B (add_23_2_n_62), .Y
       (add_23_2_n_68));
  NAND3X1 add_23_2_g297(.A (add_23_2_n_62), .B (in1[9]), .C
       (add_23_2_n_31), .Y (add_23_2_n_67));
  OAI21X1 add_23_2_g298(.A0 (add_23_2_n_28), .A1 (add_23_2_n_57), .B0
       (add_23_2_n_20), .Y (add_23_2_n_66));
  OAI21X2 add_23_2_g299(.A0 (add_23_2_n_51), .A1 (add_23_2_n_57), .B0
       (add_23_2_n_56), .Y (add_23_2_n_65));
  NOR2X6 add_23_2_g300(.A (add_23_2_n_1), .B (add_23_2_n_63), .Y
       (add_23_2_n_64));
  NOR2X6 add_23_2_g302(.A (add_23_2_n_17), .B (add_23_2_n_36), .Y
       (add_23_2_n_63));
  NAND2X1 add_23_2_g303(.A (add_23_2_n_24), .B (add_23_2_n_58), .Y
       (add_23_2_n_62));
  NAND2X1 add_23_2_g305(.A (add_23_2_n_24), .B (add_23_2_n_48), .Y
       (add_23_2_n_61));
  NAND2X1 add_23_2_g306(.A (add_23_2_n_50), .B (add_23_2_n_38), .Y
       (add_23_2_n_60));
  NAND2BX1 add_23_2_g307(.AN (add_23_2_n_28), .B (add_23_2_n_38), .Y
       (add_23_2_n_59));
  OAI21X1 add_23_2_g308(.A0 (add_23_2_n_21), .A1 (add_23_2_n_29), .B0
       (add_23_2_n_27), .Y (add_23_2_n_58));
  NOR2X2 add_23_2_g310(.A (add_23_2_n_37), .B (add_23_2_n_47), .Y
       (add_23_2_n_57));
  AOI2BB1X1 add_23_2_g311(.A0N (add_23_2_n_20), .A1N (add_23_2_n_22),
       .B0 (add_23_2_n_26), .Y (add_23_2_n_56));
  OAI21X2 add_23_2_g312(.A0 (add_23_2_n_19), .A1 (add_23_2_n_33), .B0
       (add_23_2_n_25), .Y (add_23_2_n_55));
  INVX1 add_23_2_g314(.A (add_23_2_n_52), .Y (add_23_2_n_53));
  INVX1 add_23_2_g315(.A (add_23_2_n_50), .Y (add_23_2_n_51));
  NOR2X2 add_23_2_g317(.A (add_23_2_n_30), .B (add_23_2_n_32), .Y
       (add_23_2_n_47));
  NAND2X2 add_23_2_g318(.A (add_23_2_n_34), .B (add_23_2_n_23), .Y
       (add_23_2_n_46));
  NAND2X1 add_23_2_g319(.A (add_23_2_n_31), .B (add_23_2_n_24), .Y
       (add_23_2_n_54));
  NOR2BX1 add_23_2_g320(.AN (add_23_2_n_27), .B (add_23_2_n_29), .Y
       (add_23_2_n_52));
  NOR2X1 add_23_2_g321(.A (add_23_2_n_22), .B (add_23_2_n_28), .Y
       (add_23_2_n_50));
  NOR2X1 add_23_2_g322(.A (add_23_2_n_1), .B (add_23_2_n_36), .Y
       (add_23_2_n_45));
  NAND2BX1 add_23_2_g323(.AN (add_23_2_n_18), .B (add_23_2_n_21), .Y
       (add_23_2_n_49));
  NOR2X1 add_23_2_g324(.A (add_23_2_n_29), .B (add_23_2_n_18), .Y
       (add_23_2_n_48));
  NAND2BX1 add_23_2_g333(.AN (add_23_2_n_35), .B (add_23_2_n_30), .Y
       (add_23_2_n_44));
  NAND2X1 add_23_2_g334(.A (add_23_2_n_25), .B (add_23_2_n_34), .Y
       (add_23_2_n_43));
  NOR2X1 add_23_2_g335(.A (add_23_2_n_37), .B (add_23_2_n_32), .Y
       (add_23_2_n_42));
  NAND2BX1 add_23_2_g336(.AN (add_23_2_n_28), .B (add_23_2_n_20), .Y
       (add_23_2_n_41));
  NOR2X1 add_23_2_g337(.A (add_23_2_n_26), .B (add_23_2_n_22), .Y
       (add_23_2_n_40));
  NAND2X1 add_23_2_g338(.A (add_23_2_n_19), .B (add_23_2_n_116), .Y
       (add_23_2_n_39));
  NOR2X1 add_23_2_g339(.A (add_23_2_n_32), .B (add_23_2_n_35), .Y
       (add_23_2_n_38));
  CLKINVX2 add_23_2_g340(.A (add_23_2_n_33), .Y (add_23_2_n_34));
  AND2X1 add_23_2_g341(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_37));
  NOR2X4 add_23_2_g343(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_36));
  NOR2X2 add_23_2_g344(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_35));
  NOR2X8 add_23_2_g345(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_33));
  NOR2X4 add_23_2_g346(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_32));
  NAND2X1 add_23_2_g347(.A (in2[10]), .B (in1[9]), .Y (add_23_2_n_31));
  NAND2X2 add_23_2_g348(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_30));
  NOR2X1 add_23_2_g349(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_29));
  NOR2X2 add_23_2_g350(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_28));
  NAND2X1 add_23_2_g352(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_27));
  AND2X1 add_23_2_g353(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_26));
  NAND2X1 add_23_2_g354(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_25));
  OR2X1 add_23_2_g355(.A (in2[10]), .B (in1[9]), .Y (add_23_2_n_24));
  NAND2X2 add_23_2_g356(.A (add_23_2_n_15), .B (add_23_2_n_16), .Y
       (add_23_2_n_23));
  NOR2X4 add_23_2_g357(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_22));
  NAND2X1 add_23_2_g358(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_21));
  NAND2X2 add_23_2_g359(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_20));
  NAND2X2 add_23_2_g360(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_19));
  NOR2X1 add_23_2_g361(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_18));
  NAND2X8 add_23_2_g362(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_17));
  CLKINVX2 add_23_2_g363(.A (in1[2]), .Y (add_23_2_n_16));
  CLKINVX2 add_23_2_g365(.A (in2[2]), .Y (add_23_2_n_15));
  INVX1 add_23_2_g368(.A (in1[9]), .Y (add_23_2_n_14));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_17), .B (add_23_2_n_45), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g369(.AN (add_23_2_n_57), .B (add_23_2_n_3), .Y
       (add_23_2_n_12));
  CLKXOR2X1 add_23_2_g370(.A (add_23_2_n_54), .B (add_23_2_n_83), .Y
       (out1[10]));
  CLKXOR2X1 add_23_2_g371(.A (add_23_2_n_49), .B (add_23_2_n_77), .Y
       (out1[8]));
  CLKXOR2X1 add_23_2_g372(.A (add_23_2_n_44), .B (add_23_2_n_70), .Y
       (out1[4]));
  CLKXOR2X1 add_23_2_g373(.A (add_23_2_n_43), .B (add_23_2_n_71), .Y
       (out1[3]));
  XNOR2XL add_23_2_g374(.A (add_23_2_n_42), .B (add_23_2_n_76), .Y
       (out1[5]));
  CLKXOR2X1 add_23_2_g375(.A (add_23_2_n_41), .B (add_23_2_n_12), .Y
       (out1[6]));
  XNOR2XL add_23_2_g376(.A (add_23_2_n_40), .B (add_23_2_n_75), .Y
       (out1[7]));
  CLKXOR2X1 add_23_2_g377(.A (add_23_2_n_39), .B (add_23_2_n_112), .Y
       (out1[2]));
  NOR2BX1 add_23_2_g378(.AN (add_23_2_n_38), .B (add_23_2_n_70), .Y
       (add_23_2_n_3));
  NOR2BX1 add_23_2_g379(.AN (add_23_2_n_117), .B (add_23_2_n_113), .Y
       (add_23_2_n_2));
  CLKAND2X6 add_23_2_g380(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g381(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  BUFX2 add_23_2_fopt(.A (add_23_2_n_78), .Y (add_23_2_n_109));
  INVXL add_23_2_fopt382(.A (add_23_2_n_114), .Y (add_23_2_n_112));
  INVXL add_23_2_fopt383(.A (add_23_2_n_114), .Y (add_23_2_n_113));
  INVXL add_23_2_fopt384(.A (add_23_2_n_64), .Y (add_23_2_n_114));
  INVXL add_23_2_fopt385(.A (add_23_2_n_118), .Y (add_23_2_n_116));
  INVXL add_23_2_fopt386(.A (add_23_2_n_118), .Y (add_23_2_n_117));
  INVXL add_23_2_fopt387(.A (add_23_2_n_23), .Y (add_23_2_n_118));
endmodule

