`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  5 2021 17:58:15 CST (May  5 2021 09:58:15 UTC)

module SobelFilter_Add_2Sx2U_4S_4(in2, in1, out1);
  input [1:0] in2, in1;
  output [3:0] out1;
  wire [1:0] in2, in1;
  wire [3:0] out1;
  wire add_23_2_n_0, add_23_2_n_2, add_23_2_n_4, add_23_2_n_6;
  INVX1 add_23_2_g65(.A (add_23_2_n_6), .Y (out1[2]));
  ADDHX1 add_23_2_g66(.A (in2[1]), .B (add_23_2_n_4), .CO (out1[3]), .S
       (add_23_2_n_6));
  INVX1 add_23_2_g67(.A (add_23_2_n_2), .Y (add_23_2_n_4));
  ADDFX1 add_23_2_g68(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]), .CO
       (add_23_2_n_2), .S (out1[1]));
  ADDHX1 add_23_2_g69(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule

