// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon May  3 02:43:23 2021
// from ../SobelFilter.cpp
#include "SobelFilter_rtl.h"

struct SobelFilter;
SobelFilter::SobelFilter(sc_module_name name) : sc_module(name) 
    ,i_clk("i_clk")
    ,i_rst("i_rst")
    ,i_rgb_busy("i_rgb_busy")
    ,i_rgb_vld("i_rgb_vld")
    ,i_rgb_data("i_rgb_data")
    ,o_result_r_busy("o_result_r_busy")
    ,o_result_r_vld("o_result_r_vld")
    ,o_result_r_data("o_result_r_data")
    ,o_result_g_busy("o_result_g_busy")
    ,o_result_g_vld("o_result_g_vld")
    ,o_result_g_data("o_result_g_data")
    ,o_result_b_busy("o_result_b_busy")
    ,o_result_b_vld("o_result_b_vld")
    ,o_result_b_data("o_result_b_data")
    ,o_result_b_m_req_m_prev_trig_req("o_result_b_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_1_7_out1("SobelFilter_Xor_1Ux1U_1U_1_7_out1")
    ,o_result_b_m_unacked_req("o_result_b_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_8_out1("SobelFilter_Or_1Ux1U_1U_4_8_out1")
    ,o_result_g_m_req_m_prev_trig_req("o_result_g_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_1_4_out1("SobelFilter_Xor_1Ux1U_1U_1_4_out1")
    ,o_result_g_m_unacked_req("o_result_g_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_5_out1("SobelFilter_Or_1Ux1U_1U_4_5_out1")
    ,o_result_r_m_req_m_prev_trig_req("o_result_r_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_1_1_out1("SobelFilter_Xor_1Ux1U_1U_1_1_out1")
    ,o_result_r_m_unacked_req("o_result_r_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_2_out1("SobelFilter_Or_1Ux1U_1U_4_2_out1")
    ,SobelFilter_N_Muxb_1_2_23_4_10_out1("SobelFilter_N_Muxb_1_2_23_4_10_out1")
    ,i_rgb_m_unvalidated_req("i_rgb_m_unvalidated_req")
    ,SobelFilter_gen_busy_r_4_61_gen_busy_i_rgb_m_data_is_invalid_next("SobelFilter_gen_busy_r_4_61_gen_busy_i_rgb_m_data_is_invalid_next")
    ,SobelFilter_gen_busy_r_4_61_gdiv("SobelFilter_gen_busy_r_4_61_gdiv")
    ,SobelFilter_gen_busy_r_4_61_gnew_req("SobelFilter_gen_busy_r_4_61_gnew_req")
    ,global_state_next("global_state_next")
    ,SobelFilter_gen000001_4_43_in1("SobelFilter_gen000001_4_43_in1")
    ,gs_ctrl19("gs_ctrl19")
    ,SobelFilter_Add2Mul2s8u8s8_4_30_in3("SobelFilter_Add2Mul2s8u8s8_4_30_in3")
    ,gs_ctrl18("gs_ctrl18")
    ,SobelFilter_Div_8U_27_4_29_out1("SobelFilter_Div_8U_27_4_29_out1")
    ,SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_out1("SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_out1")
    ,bits_001("bits_001")
    ,SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_in1("SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_in1")
    ,gs_ctrl17("gs_ctrl17")
    ,SobelFilter_Add2u2Mul2i3u2_4_22_out1("SobelFilter_Add2u2Mul2i3u2_4_22_out1")
    ,SobelFilter_Add2u2Mul2i3u2_4_22_in1("SobelFilter_Add2u2Mul2i3u2_4_22_in1")
    ,SobelFilter_Add2u2Mul2i3u2_4_22_in2("SobelFilter_Add2u2Mul2i3u2_4_22_in2")
    ,gs_ctrl15("gs_ctrl15")
    ,SobelFilter_Add3u9u2Cati0u2_4_21_in1("SobelFilter_Add3u9u2Cati0u2_4_21_in1")
    ,gs_ctrl14("gs_ctrl14")
    ,SobelFilter_Add3u9u2Cati0u2_4_21_in2("SobelFilter_Add3u9u2Cati0u2_4_21_in2")
    ,SobelFilter_Add3u9u2Cati0u2_4_21_in3("SobelFilter_Add3u9u2Cati0u2_4_21_in3")
    ,gs_ctrl12("gs_ctrl12")
    ,SobelFilter_Lti2s3_4_15_out1("SobelFilter_Lti2s3_4_15_out1")
    ,gs_ctrl10("gs_ctrl10")
    ,gs_ctrl8("gs_ctrl8")
    ,gs_ctrl6("gs_ctrl6")
    ,gs_ctrl4("gs_ctrl4")
    ,gs_ctrl3("gs_ctrl3")
    ,gs_ctrl2("gs_ctrl2")
    ,SobelFilter_Lti3u2_4_38_out1("SobelFilter_Lti3u2_4_38_out1")
    ,gs_ctrl1("gs_ctrl1")
    ,gs_ctrl0("gs_ctrl0")
    ,SobelFilter_Add2iLLu9_4_18_out1("SobelFilter_Add2iLLu9_4_18_out1")
    ,SobelFilter_Add3u9u2Cati0u2_4_21_out1("SobelFilter_Add3u9u2Cati0u2_4_21_out1")
    ,SobelFilter_gen000001_4_43_out1("SobelFilter_gen000001_4_43_out1")
    ,SobelFilter_Add2iLLu9_4_53_out1("SobelFilter_Add2iLLu9_4_53_out1")
    ,SobelFilter_gen000001_4_49_out1("SobelFilter_gen000001_4_49_out1")
    ,s_reg_45("s_reg_45")
    ,s_reg_44("s_reg_44")
    ,s_reg_42("s_reg_42")
    ,s_reg_41("s_reg_41")
    ,SobelFilter_Add2i1u2_4_26_out1("SobelFilter_Add2i1u2_4_26_out1")
    ,s_reg_40("s_reg_40")
    ,SobelFilter_Add2i1u2_4_25_out1("SobelFilter_Add2i1u2_4_25_out1")
    ,SobelFilter_Add2i1u1_4_12_out1("SobelFilter_Add2i1u1_4_12_out1")
    ,s_reg_43("s_reg_43")
    ,SobelFilter_Add2i1u9_4_13_out1("SobelFilter_Add2i1u9_4_13_out1")
    ,s_reg_38("s_reg_38")
    ,SobelFilter_Lti3u2_4_34_out1("SobelFilter_Lti3u2_4_34_out1")
    ,s_reg_39("s_reg_39")
    ,SobelFilter_LtiLLs11_4_14_out1("SobelFilter_LtiLLs11_4_14_out1")
    ,s_reg_37_slice("s_reg_37_slice")
    ,SobelFilter_gen_busy_r_4_61_out1("SobelFilter_gen_busy_r_4_61_out1")
    ,SobelFilter_And_1Ux1U_1U_4_57_out1("SobelFilter_And_1Ux1U_1U_4_57_out1")
    ,SobelFilter_And_1Ux1U_1U_4_58_out1("SobelFilter_And_1Ux1U_1U_4_58_out1")
    ,SobelFilter_And_1Ux1U_1U_4_59_out1("SobelFilter_And_1Ux1U_1U_4_59_out1")
    ,SobelFilter_Not_1U_1U_1_9_out1("SobelFilter_Not_1U_1U_1_9_out1")
    ,o_result_b_m_req_m_trig_req("o_result_b_m_req_m_trig_req")
    ,SobelFilter_Not_1U_1U_1_6_out1("SobelFilter_Not_1U_1U_1_6_out1")
    ,o_result_g_m_req_m_trig_req("o_result_g_m_req_m_trig_req")
    ,SobelFilter_Not_1U_1U_1_3_out1("SobelFilter_Not_1U_1U_1_3_out1")
    ,o_result_r_m_req_m_trig_req("o_result_r_m_req_m_trig_req")
    ,SobelFilter_LtiLLs11_4_56_out1("SobelFilter_LtiLLs11_4_56_out1")
    ,i_rgb_m_busy_req_0("i_rgb_m_busy_req_0")
    ,SobelFilter_Add2n128s8_4_39_out1("SobelFilter_Add2n128s8_4_39_out1")
    ,SobelFilter_Add2n128s8_4_40_out1("SobelFilter_Add2n128s8_4_40_out1")
    ,SobelFilter_LtiLLs11_4_42_out1("SobelFilter_LtiLLs11_4_42_out1")
    ,SobelFilter_Add2n128s8_4_41_out1("SobelFilter_Add2n128s8_4_41_out1")
    ,SobelFilter_Add2Mul2s8u8s8_4_30_out1("SobelFilter_Add2Mul2s8u8s8_4_30_out1")
    ,SobelFilter_LtiLLs11_4_20_out1("SobelFilter_LtiLLs11_4_20_out1")
    ,global_state("global_state")
    ,stall0("stall0")
    ,filter2_in1("filter2_in1")
    ,filter2_out1("filter2_out1")
    ,from_tb_b_DIN("from_tb_b_DIN")
    ,from_tb_b_CE("from_tb_b_CE")
    ,from_tb_b_RW("from_tb_b_RW")
    ,from_tb_b_in1("from_tb_b_in1")
    ,from_tb_b_out1("from_tb_b_out1")
    ,from_tb_g_DIN("from_tb_g_DIN")
    ,from_tb_g_CE("from_tb_g_CE")
    ,from_tb_g_RW("from_tb_g_RW")
    ,from_tb_g_in1("from_tb_g_in1")
    ,from_tb_g_out1("from_tb_g_out1")
    ,from_tb_r_DIN("from_tb_r_DIN")
    ,from_tb_r_CE("from_tb_r_CE")
    ,from_tb_r_RW("from_tb_r_RW")
    ,from_tb_r_in1("from_tb_r_in1")
    ,from_tb_r_out1("from_tb_r_out1")
{
  from_tb_r = new SobelFilter_RAM_1536X8_1("from_tb_r");
  from_tb_r->DIN(from_tb_r_DIN);
  from_tb_r->CE(from_tb_r_CE);
  from_tb_r->RW(from_tb_r_RW);
  from_tb_r->in1(from_tb_r_in1);
  from_tb_r->out1(from_tb_r_out1);
  from_tb_r->clk(i_clk);

  from_tb_g = new SobelFilter_RAM_1536X8_1("from_tb_g");
  from_tb_g->DIN(from_tb_g_DIN);
  from_tb_g->CE(from_tb_g_CE);
  from_tb_g->RW(from_tb_g_RW);
  from_tb_g->in1(from_tb_g_in1);
  from_tb_g->out1(from_tb_g_out1);
  from_tb_g->clk(i_clk);

  from_tb_b = new SobelFilter_RAM_1536X8_1("from_tb_b");
  from_tb_b->DIN(from_tb_b_DIN);
  from_tb_b->CE(from_tb_b_CE);
  from_tb_b->RW(from_tb_b_RW);
  from_tb_b->in1(from_tb_b_in1);
  from_tb_b->out1(from_tb_b_out1);
  from_tb_b->clk(i_clk);

  filter2 = new SobelFilter_ROM_9X32_filter2("filter2");
  filter2->in1(filter2_in1);
  filter2->out1(filter2_out1);
  filter2->clk(i_clk);

  SC_METHOD(drive_o_result_b_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_g_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_r_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_r_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_g_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_b_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( SobelFilter_gen_busy_r_4_61_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_57_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_58_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_59_out1 );

  SC_METHOD(drive_s_reg_37_slice);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_38);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_39);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_40);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_41);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_42);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_43);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_44);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_45);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Add2i1u1_4_12);
  sensitive << ( s_reg_37_slice );

  SC_METHOD(SobelFilter_Add2i1u9_4_13);
  sensitive << ( s_reg_38 );

  SC_METHOD(SobelFilter_LtiLLs11_4_14);
  sensitive << ( s_reg_38 );

  SC_METHOD(drive_from_tb_r_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_38 );
  sensitive << ( s_reg_37_slice );
  sensitive << ( SobelFilter_Add2iLLu9_4_18_out1 );
  sensitive << ( SobelFilter_Add3u9u2Cati0u2_4_21_out1 );
  sensitive << ( SobelFilter_LtiLLs11_4_42_out1 );
  sensitive << ( SobelFilter_gen000001_4_43_out1 );
  sensitive << ( SobelFilter_Add2iLLu9_4_53_out1 );
  sensitive << ( SobelFilter_gen000001_4_49_out1 );

  SC_METHOD(drive_from_tb_r_DIN);
  sensitive << ( gs_ctrl1 );
  sensitive << ( i_rgb_data );
  sensitive << ( from_tb_r_out1 );

  SC_METHOD(drive_from_tb_r_CE);
  sensitive << ( stall0 );
  sensitive << ( gs_ctrl2 );
  sensitive << ( SobelFilter_LtiLLs11_4_20_out1 );
  sensitive << ( SobelFilter_Lti3u2_4_34_out1 );
  sensitive << ( SobelFilter_Lti3u2_4_38_out1 );
  sensitive << ( SobelFilter_LtiLLs11_4_56_out1 );

  SC_METHOD(drive_from_tb_r_RW);
  sensitive << ( stall0 );
  sensitive << ( gs_ctrl3 );

  SC_METHOD(drive_from_tb_g_in1);
  sensitive << ( gs_ctrl4 );
  sensitive << ( s_reg_38 );
  sensitive << ( s_reg_37_slice );
  sensitive << ( SobelFilter_Add2iLLu9_4_18_out1 );
  sensitive << ( SobelFilter_Add3u9u2Cati0u2_4_21_out1 );
  sensitive << ( SobelFilter_gen000001_4_43_out1 );
  sensitive << ( SobelFilter_Add2iLLu9_4_53_out1 );
  sensitive << ( SobelFilter_gen000001_4_49_out1 );

  SC_METHOD(drive_from_tb_g_DIN);
  sensitive << ( gs_ctrl1 );
  sensitive << ( i_rgb_data );
  sensitive << ( from_tb_g_out1 );

  SC_METHOD(drive_from_tb_g_CE);
  sensitive << ( stall0 );
  sensitive << ( gs_ctrl6 );
  sensitive << ( SobelFilter_LtiLLs11_4_42_out1 );
  sensitive << ( SobelFilter_LtiLLs11_4_56_out1 );

  SC_METHOD(drive_from_tb_g_RW);
  sensitive << ( stall0 );
  sensitive << ( gs_ctrl3 );

  SC_METHOD(drive_from_tb_b_in1);
  sensitive << ( gs_ctrl8 );
  sensitive << ( s_reg_38 );
  sensitive << ( s_reg_37_slice );
  sensitive << ( SobelFilter_Add2iLLu9_4_18_out1 );
  sensitive << ( SobelFilter_Add3u9u2Cati0u2_4_21_out1 );
  sensitive << ( SobelFilter_gen000001_4_43_out1 );
  sensitive << ( SobelFilter_Add2iLLu9_4_53_out1 );
  sensitive << ( SobelFilter_gen000001_4_49_out1 );

  SC_METHOD(drive_from_tb_b_DIN);
  sensitive << ( gs_ctrl1 );
  sensitive << ( i_rgb_data );
  sensitive << ( from_tb_b_out1 );

  SC_METHOD(drive_from_tb_b_CE);
  sensitive << ( stall0 );
  sensitive << ( gs_ctrl10 );
  sensitive << ( SobelFilter_LtiLLs11_4_42_out1 );
  sensitive << ( SobelFilter_LtiLLs11_4_56_out1 );

  SC_METHOD(drive_from_tb_b_RW);
  sensitive << ( stall0 );
  sensitive << ( gs_ctrl3 );

  SC_METHOD(SobelFilter_Lti2s3_4_15);
  sensitive << ( s_reg_39 );

  SC_METHOD(SobelFilter_Add2iLLu9_4_18);
  sensitive << ( s_reg_38 );

  SC_METHOD(SobelFilter_LtiLLs11_4_20);
  sensitive << ( s_reg_38 );

  SC_METHOD(drive_SobelFilter_Add3u9u2Cati0u2_4_21_in3);
  sensitive << ( gs_ctrl12 );
  sensitive << ( s_reg_37_slice );
  sensitive << ( SobelFilter_Lti3u2_4_34_out1 );
  sensitive << ( s_reg_39 );

  SC_METHOD(drive_SobelFilter_Add3u9u2Cati0u2_4_21_in2);
  sensitive << ( gs_ctrl12 );
  sensitive << ( s_reg_40 );
  sensitive << ( SobelFilter_Lti3u2_4_34_out1 );

  SC_METHOD(drive_SobelFilter_Add3u9u2Cati0u2_4_21_in1);
  sensitive << ( gs_ctrl14 );
  sensitive << ( s_reg_38 );
  sensitive << ( s_reg_43 );

  SC_METHOD(SobelFilter_Add3u9u2Cati0u2_4_21);
  sensitive << ( SobelFilter_Add3u9u2Cati0u2_4_21_in1 );
  sensitive << ( SobelFilter_Add3u9u2Cati0u2_4_21_in2 );
  sensitive << ( SobelFilter_Add3u9u2Cati0u2_4_21_in3 );

  SC_METHOD(drive_SobelFilter_Add2u2Mul2i3u2_4_22_in2);
  sensitive << ( gs_ctrl15 );
  sensitive << ( SobelFilter_Lti3u2_4_34_out1 );
  sensitive << ( s_reg_37_slice );
  sensitive << ( s_reg_39 );

  SC_METHOD(drive_SobelFilter_Add2u2Mul2i3u2_4_22_in1);
  sensitive << ( gs_ctrl15 );
  sensitive << ( SobelFilter_Lti3u2_4_34_out1 );
  sensitive << ( s_reg_40 );

  SC_METHOD(SobelFilter_Add2u2Mul2i3u2_4_22);
  sensitive << ( SobelFilter_Add2u2Mul2i3u2_4_22_in1 );
  sensitive << ( SobelFilter_Add2u2Mul2i3u2_4_22_in2 );

  SC_METHOD(drive_filter2_in1);
  sensitive << ( SobelFilter_Add2u2Mul2i3u2_4_22_out1 );

  SC_METHOD(SobelFilter_Add2i1u2_4_25);
  sensitive << ( s_reg_37_slice );

  SC_METHOD(SobelFilter_Add2i1u2_4_26);
  sensitive << ( s_reg_40 );

  SC_METHOD(drive_SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_in1);
  sensitive << ( gs_ctrl17 );
  sensitive << ( s_reg_45 );
  sensitive << ( from_tb_b_out1 );

  SC_METHOD(drive_bits_001);
  sensitive << ( SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_in1 );
  sensitive << ( s_reg_44 );
  sensitive << ( s_reg_41 );

  SC_METHOD(SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28);
  sensitive << ( bits_001 );

  SC_METHOD(SobelFilter_Div_8U_27_4_29);
  sensitive << ( SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_out1 );

  SC_METHOD(drive_SobelFilter_Add2Mul2s8u8s8_4_30_in3);
  sensitive << ( gs_ctrl18 );
  sensitive << ( o_result_r_data );
  sensitive << ( o_result_g_data );
  sensitive << ( o_result_b_data );

  SC_METHOD(SobelFilter_Add2Mul2s8u8s8_4_30);
  sensitive << ( s_reg_42 );
  sensitive << ( SobelFilter_Div_8U_27_4_29_out1 );
  sensitive << ( SobelFilter_Add2Mul2s8u8s8_4_30_in3 );

  SC_METHOD(SobelFilter_Lti3u2_4_34);
  sensitive << ( s_reg_40 );

  SC_METHOD(SobelFilter_Lti3u2_4_38);
  sensitive << ( s_reg_39 );

  SC_METHOD(SobelFilter_Add2n128s8_4_39);
  sensitive << ( o_result_r_data );

  SC_METHOD(SobelFilter_Add2n128s8_4_40);
  sensitive << ( o_result_g_data );

  SC_METHOD(SobelFilter_Add2n128s8_4_41);
  sensitive << ( o_result_b_data );

  SC_METHOD(SobelFilter_LtiLLs11_4_42);
  sensitive << ( s_reg_43 );

  SC_METHOD(drive_SobelFilter_gen000001_4_43_in1);
  sensitive << ( gs_ctrl19 );
  sensitive << ( s_reg_38 );

  SC_METHOD(SobelFilter_gen000001_4_43);
  sensitive << ( SobelFilter_gen000001_4_43_in1 );

  SC_METHOD(SobelFilter_Add2iLLu9_4_53);
  sensitive << ( s_reg_38 );

  SC_METHOD(SobelFilter_gen000001_4_49);
  sensitive << ( s_reg_38 );

  SC_METHOD(SobelFilter_LtiLLs11_4_56);
  sensitive << ( s_reg_38 );

  SC_METHOD(drive_global_state);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );
  sensitive << ( SobelFilter_LtiLLs11_4_14_out1 );
  sensitive << ( SobelFilter_Lti2s3_4_15_out1 );
  sensitive << ( SobelFilter_LtiLLs11_4_20_out1 );
  sensitive << ( SobelFilter_Lti3u2_4_34_out1 );
  sensitive << ( SobelFilter_Lti3u2_4_38_out1 );
  sensitive << ( SobelFilter_LtiLLs11_4_42_out1 );
  sensitive << ( SobelFilter_LtiLLs11_4_56_out1 );

  SC_METHOD(drive_gs_ctrl0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl1);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl2);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl3);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl4);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl6);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl8);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl10);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl12);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl14);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl15);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl17);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl18);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl19);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_busy);
  sensitive << ( SobelFilter_gen_busy_r_4_61_out1 );

  SC_METHOD(SobelFilter_gen_busy_r_4_61_p8);
  sensitive << ( 
  SobelFilter_gen_busy_r_4_61_gen_busy_i_rgb_m_data_is_invalid_next );
  sensitive << ( SobelFilter_gen_busy_r_4_61_gdiv );
  sensitive << ( SobelFilter_gen_busy_r_4_61_gnew_req );

  SC_METHOD(SobelFilter_gen_busy_r_4_61_p7);
  sensitive << ( SobelFilter_gen_busy_r_4_61_gdiv );

  SC_METHOD(SobelFilter_gen_busy_r_4_61_p6);
  sensitive << ( SobelFilter_gen_busy_r_4_61_gnew_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(SobelFilter_gen_busy_r_4_61_p5);
  sensitive << ( i_rgb_vld );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_m_busy_req_0 );

  SC_METHOD(drive_i_rgb_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_N_Muxb_1_2_23_4_10);
  sensitive << ( i_rgb_m_busy_req_0 );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(drive_o_result_r_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_2_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_2);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_1_1_out1 );
  sensitive << ( o_result_r_m_unacked_req );

  SC_METHOD(drive_o_result_r_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_57);
  sensitive << ( o_result_r_vld );
  sensitive << ( o_result_r_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_1_1);
  sensitive << ( o_result_r_m_req_m_prev_trig_req );
  sensitive << ( o_result_r_m_req_m_trig_req );

  SC_METHOD(drive_o_result_r_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_1_3);
  sensitive << ( o_result_r_m_req_m_trig_req );

  SC_METHOD(drive_o_result_g_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_5_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_5);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_1_4_out1 );
  sensitive << ( o_result_g_m_unacked_req );

  SC_METHOD(drive_o_result_g_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_58);
  sensitive << ( o_result_g_vld );
  sensitive << ( o_result_g_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_1_4);
  sensitive << ( o_result_g_m_req_m_prev_trig_req );
  sensitive << ( o_result_g_m_req_m_trig_req );

  SC_METHOD(drive_o_result_g_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_1_6);
  sensitive << ( o_result_g_m_req_m_trig_req );

  SC_METHOD(drive_o_result_b_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_8_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_8);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_1_7_out1 );
  sensitive << ( o_result_b_m_unacked_req );

  SC_METHOD(drive_o_result_b_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_59);
  sensitive << ( o_result_b_vld );
  sensitive << ( o_result_b_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_1_7);
  sensitive << ( o_result_b_m_req_m_prev_trig_req );
  sensitive << ( o_result_b_m_req_m_trig_req );

  SC_METHOD(drive_o_result_b_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_1_9);
  sensitive << ( o_result_b_m_req_m_trig_req );

}
// resource: mux_8bx3i1c
// resource: regr_en_8
void SobelFilter::drive_o_result_b_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 4ULL: 
      if ( SobelFilter_LtiLLs11_4_20_out1.read() );
      else {
        o_result_b_data = 0ULL;
      }
      break;
    case 9ULL: 
      /* state21 */
      o_result_b_data = (sc_uint<8> ) (SobelFilter_Add2Mul2s8u8s8_4_30_out1
                        .read());
      break;
    case 13ULL: 
      o_result_b_data = (sc_uint<8> ) (SobelFilter_Add2n128s8_4_41_out1.read());
      break;
    case 15ULL: 
      if ( SobelFilter_LtiLLs11_4_42_out1.read() ) {
        o_result_b_data = 0ULL;
      } 
      break;
    }
    break;
  }
}
// resource: mux_8bx3i1c
// resource: regr_en_8
void SobelFilter::drive_o_result_g_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 4ULL: 
      if ( SobelFilter_LtiLLs11_4_20_out1.read() );
      else {
        o_result_g_data = 0ULL;
      }
      break;
    case 8ULL: 
      o_result_g_data = (sc_uint<8> ) (SobelFilter_Add2Mul2s8u8s8_4_30_out1
                        .read());
      break;
    case 12ULL: 
      o_result_g_data = (sc_uint<8> ) (SobelFilter_Add2n128s8_4_40_out1.read());
      break;
    case 15ULL: 
      if ( SobelFilter_LtiLLs11_4_42_out1.read() ) {
        o_result_g_data = 0ULL;
      } 
      break;
    }
    break;
  }
}
// resource: mux_8bx3i1c
// resource: regr_en_8
void SobelFilter::drive_o_result_r_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 4ULL: 
      if ( SobelFilter_LtiLLs11_4_20_out1.read() );
      else {
        o_result_r_data = 0ULL;
      }
      break;
    case 7ULL: 
      o_result_r_data = (sc_uint<8> ) (SobelFilter_Add2Mul2s8u8s8_4_30_out1
                        .read());
      break;
    case 11ULL: 
      o_result_r_data = (sc_uint<8> ) (SobelFilter_Add2n128s8_4_39_out1.read());
      break;
    case 15ULL: 
      if ( SobelFilter_LtiLLs11_4_42_out1.read() ) {
        o_result_r_data = 0ULL;
      } 
      break;
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void SobelFilter::drive_i_rgb_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state.read()) ) {
      case 0ULL: case 2ULL: 
        i_rgb_m_busy_req_0 = 0ULL;
        break;
      case 1ULL: case 3ULL: 
        i_rgb_m_busy_req_0 = 1ULL;
        break;
      case 4ULL: 
        if ( SobelFilter_LtiLLs11_4_20_out1.read() ) {
          i_rgb_m_busy_req_0 = 0ULL;
        } 
        break;
      case 20ULL: 
        if ( SobelFilter_LtiLLs11_4_56_out1.read() );
        else {
          i_rgb_m_busy_req_0 = 0ULL;
        }
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void SobelFilter::drive_o_result_r_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_r_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state.read()) ) {
      case 11ULL: 
        o_result_r_m_req_m_trig_req = (sc_uint<1> ) (
                                      SobelFilter_Not_1U_1U_1_3_out1.read());
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void SobelFilter::drive_o_result_g_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_g_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state.read()) ) {
      case 12ULL: 
        o_result_g_m_req_m_trig_req = (sc_uint<1> ) (
                                      SobelFilter_Not_1U_1U_1_6_out1.read());
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void SobelFilter::drive_o_result_b_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_b_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state.read()) ) {
      case 13ULL: 
        o_result_b_m_req_m_trig_req = (sc_uint<1> ) (
                                      SobelFilter_Not_1U_1U_1_9_out1.read());
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx5i1c
void SobelFilter::drive_stall0(){
  switch( (sc_uint<5>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 1ULL: case 3ULL: 
    stall0 = (sc_uint<1> )SobelFilter_gen_busy_r_4_61_out1.read();
    break;
  case 12ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_57_out1.read();
    break;
  case 13ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_58_out1.read();
    break;
  case 14ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_59_out1.read();
    break;
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void SobelFilter::drive_s_reg_37_slice(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 0ULL: case 4ULL: case 15ULL: 
      s_reg_37_slice = 0ULL;
      break;
    case 2ULL: 
      if ( SobelFilter_LtiLLs11_4_14_out1.read() );
      else {
        s_reg_37_slice = (sc_uint<2> )s_reg_39.read();
      }
      break;
    case 9ULL: 
      if ( SobelFilter_Lti3u2_4_34_out1.read() );
      else {
        s_reg_37_slice = (sc_uint<2> )s_reg_39.read();
      }
      break;
    }
    break;
  }
}
// resource: mux_11bx3i1c
// resource: regr_en_11
void SobelFilter::drive_s_reg_38(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 0ULL: 
      s_reg_38 = 0ULL;
      break;
    case 1ULL: case 3ULL: case 19ULL: 
      s_reg_38 = (sc_uint<11> ) (SobelFilter_Add2i1u9_4_13_out1.read());
      break;
    case 2ULL: 
      if ( SobelFilter_LtiLLs11_4_14_out1.read() );
      else {
        s_reg_38 = 0ULL;
      }
      break;
    case 4ULL: 
      if ( SobelFilter_LtiLLs11_4_20_out1.read() );
      else {
        s_reg_38 = 0ULL;
      }
      break;
    case 15ULL: 
      if ( SobelFilter_LtiLLs11_4_42_out1.read() ) {
        s_reg_38 = s_reg_43.read();
      } else {
        s_reg_38 = 0ULL;
      }
      break;
    case 20ULL: 
      if ( SobelFilter_LtiLLs11_4_56_out1.read() );
      else {
        s_reg_38 = 0ULL;
      }
      break;
    }
    break;
  }
}
// resource: mux_3bx2i0c
// resource: regr_en_3
void SobelFilter::drive_s_reg_39(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 1ULL: 
      s_reg_39 = (sc_uint<3> ) (SobelFilter_Add2i1u1_4_12_out1.read());
      break;
    case 6ULL: 
      s_reg_39 = (sc_uint<3> ) (SobelFilter_Add2i1u2_4_25_out1.read());
      break;
    }
    break;
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void SobelFilter::drive_s_reg_40(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 4ULL: case 15ULL: 
      s_reg_40 = 0ULL;
      break;
    case 6ULL: 
      s_reg_40 = SobelFilter_Add2i1u2_4_26_out1.read();
      break;
    case 9ULL: 
      if ( SobelFilter_Lti3u2_4_34_out1.read() );
      else {
        s_reg_40 = 0ULL;
      }
      break;
    }
    break;
  }
}
// resource: regr_en_8
void SobelFilter::drive_s_reg_41(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 5ULL: 
      s_reg_41 = from_tb_r_out1.read();
      break;
    }
    break;
  }
}
// resource: regr_en_8
void SobelFilter::drive_s_reg_42(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 5ULL: 
      s_reg_42 = (sc_uint<8> )filter2_out1.read();
      break;
    }
    break;
  }
}
// resource: regr_en_11
void SobelFilter::drive_s_reg_43(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 6ULL: 
      s_reg_43 = (sc_uint<11> ) (SobelFilter_Add2i1u9_4_13_out1.read());
      break;
    }
    break;
  }
}
// resource: regr_en_8
void SobelFilter::drive_s_reg_44(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 6ULL: 
      s_reg_44 = from_tb_g_out1.read();
      break;
    }
    break;
  }
}
// resource: regr_en_8
void SobelFilter::drive_s_reg_45(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<5>)(global_state.read()) ) {
    case 7ULL: 
      s_reg_45 = from_tb_b_out1.read();
      break;
    }
    break;
  }
}
// resource: SobelFilter_Add2i1u1_4  instance: SobelFilter_Add2i1u1_4_12
void SobelFilter::SobelFilter_Add2i1u1_4_12(){
  SobelFilter_Add2i1u1_4_12_out1 = (/*cliff*/sc_int<32>)((sc_uint<1> )
                                   s_reg_37_slice.read() + 1LL);
}
// resource: SobelFilter_Add2i1u9_4  instance: SobelFilter_Add2i1u9_4_13
void SobelFilter::SobelFilter_Add2i1u9_4_13(){
  SobelFilter_Add2i1u9_4_13_out1 = (/*cliff*/sc_int<32>)((sc_uint<9> )s_reg_38
                                   .read() + 1LL);
}
// resource: SobelFilter_LtiLLs11_4  instance: SobelFilter_LtiLLs11_4_14
void SobelFilter::SobelFilter_LtiLLs11_4_14(){
  SobelFilter_LtiLLs11_4_14_out1 = (/*imp*/sc_uint<1>)((sc_int<11> )s_reg_38
                                   .read() < (sc_int<11> )512LL);
}
// resource: mux_11bx7i0c
void SobelFilter::drive_from_tb_r_in1(){
  switch( (sc_uint<3>)(gs_ctrl0.read()) ) {
  default:
    from_tb_r_in1 = (sc_uint<11> ) (( (sc_uint<10> )(sc_bv<10>)((sc_bv<1>)((
                    sc_uint<1> )s_reg_37_slice.read()), 
                    (sc_bv<9>)((sc_uint<9> )s_reg_38.read())) ));
    break;
  case 1ULL: 
    from_tb_r_in1 = SobelFilter_Add2iLLu9_4_18_out1.read();
    break;
  case 2ULL: 
    from_tb_r_in1 = SobelFilter_Add3u9u2Cati0u2_4_21_out1.read();
    break;
  case 3ULL: 
    if ( SobelFilter_LtiLLs11_4_42_out1.read() ) {
      from_tb_r_in1 = SobelFilter_Add3u9u2Cati0u2_4_21_out1.read();
    } else {
      from_tb_r_in1 = SobelFilter_gen000001_4_43_out1.read();
    }
    break;
  case 4ULL: 
    from_tb_r_in1 = (sc_uint<11> ) ((sc_uint<9> )s_reg_38.read());
    break;
  case 5ULL: 
    from_tb_r_in1 = SobelFilter_Add2iLLu9_4_53_out1.read();
    break;
  case 6ULL: 
    from_tb_r_in1 = SobelFilter_gen000001_4_49_out1.read();
    break;
  case 7ULL: 
    from_tb_r_in1 = SobelFilter_gen000001_4_43_out1.read();
    break;
  }
}
// resource: mux_8bx3i1c
void SobelFilter::drive_from_tb_r_DIN(){
  switch( (sc_uint<2>)(gs_ctrl1.read()) ) {
  default:
    from_tb_r_DIN = (sc_uint<8> )i_rgb_data.read();
    break;
  case 1ULL: 
    from_tb_r_DIN = from_tb_r_out1.read();
    break;
  case 2ULL: 
    from_tb_r_DIN = 0ULL;
    break;
  }
}
// resource: mux_1bx2i2c
void SobelFilter::drive_from_tb_r_CE(){
  if ( stall0.read() ) {
    from_tb_r_CE = 0ULL;
  } else {
    switch( (sc_uint<3>)(gs_ctrl2.read()) ) {
    default:
      from_tb_r_CE = 0ULL;
      break;
    case 1ULL: 
      from_tb_r_CE = 1ULL;
      break;
    case 2ULL: 
      if ( SobelFilter_LtiLLs11_4_20_out1.read() ) {
        from_tb_r_CE = 0ULL;
      } else {
        from_tb_r_CE = 1ULL;
      }
      break;
    case 3ULL: 
      if ( SobelFilter_Lti3u2_4_34_out1.read() ) {
        from_tb_r_CE = 1ULL;
      } else {
        if ( SobelFilter_Lti3u2_4_38_out1.read() ) {
          from_tb_r_CE = 1ULL;
        } else {
          from_tb_r_CE = 0ULL;
        }
      }
      break;
    case 4ULL: 
      if ( SobelFilter_LtiLLs11_4_56_out1.read() ) {
        from_tb_r_CE = 1ULL;
      } else {
        from_tb_r_CE = 0ULL;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
void SobelFilter::drive_from_tb_r_RW(){
  if ( stall0.read() ) {
    from_tb_r_RW = 0ULL;
  } else {
    if ( gs_ctrl3.read() ) {
      from_tb_r_RW = 1ULL;
    } else {
      from_tb_r_RW = 0ULL;
    }
  }
}
// resource: mux_11bx7i0c
void SobelFilter::drive_from_tb_g_in1(){
  switch( (sc_uint<3>)(gs_ctrl4.read()) ) {
  default:
    from_tb_g_in1 = (sc_uint<11> ) (( (sc_uint<10> )(sc_bv<10>)((sc_bv<1>)((
                    sc_uint<1> )s_reg_37_slice.read()), 
                    (sc_bv<9>)((sc_uint<9> )s_reg_38.read())) ));
    break;
  case 1ULL: 
    from_tb_g_in1 = SobelFilter_Add2iLLu9_4_18_out1.read();
    break;
  case 2ULL: 
    from_tb_g_in1 = SobelFilter_Add3u9u2Cati0u2_4_21_out1.read();
    break;
  case 3ULL: 
    from_tb_g_in1 = SobelFilter_gen000001_4_43_out1.read();
    break;
  case 4ULL: 
    from_tb_g_in1 = (sc_uint<11> ) ((sc_uint<9> )s_reg_38.read());
    break;
  case 5ULL: 
    from_tb_g_in1 = SobelFilter_Add2iLLu9_4_53_out1.read();
    break;
  case 6ULL: 
    from_tb_g_in1 = SobelFilter_gen000001_4_49_out1.read();
    break;
  }
}
// resource: mux_8bx3i1c
void SobelFilter::drive_from_tb_g_DIN(){
  switch( (sc_uint<2>)(gs_ctrl1.read()) ) {
  default:
    from_tb_g_DIN = (sc_uint<8> ) (i_rgb_data.read().range(15,8));
    break;
  case 1ULL: 
    from_tb_g_DIN = from_tb_g_out1.read();
    break;
  case 2ULL: 
    from_tb_g_DIN = 0ULL;
    break;
  }
}
// resource: mux_1bx2i2c
void SobelFilter::drive_from_tb_g_CE(){
  if ( stall0.read() ) {
    from_tb_g_CE = 0ULL;
  } else {
    switch( (sc_uint<2>)(gs_ctrl6.read()) ) {
    default:
      from_tb_g_CE = 0ULL;
      break;
    case 1ULL: 
      from_tb_g_CE = 1ULL;
      break;
    case 2ULL: 
      if ( SobelFilter_LtiLLs11_4_42_out1.read() ) {
        from_tb_g_CE = 0ULL;
      } else {
        from_tb_g_CE = 1ULL;
      }
      break;
    case 3ULL: 
      if ( SobelFilter_LtiLLs11_4_56_out1.read() ) {
        from_tb_g_CE = 1ULL;
      } else {
        from_tb_g_CE = 0ULL;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
void SobelFilter::drive_from_tb_g_RW(){
  if ( stall0.read() ) {
    from_tb_g_RW = 0ULL;
  } else {
    if ( gs_ctrl3.read() ) {
      from_tb_g_RW = 1ULL;
    } else {
      from_tb_g_RW = 0ULL;
    }
  }
}
// resource: mux_11bx7i0c
void SobelFilter::drive_from_tb_b_in1(){
  switch( (sc_uint<3>)(gs_ctrl8.read()) ) {
  default:
    from_tb_b_in1 = (sc_uint<11> ) (( (sc_uint<10> )(sc_bv<10>)((sc_bv<1>)((
                    sc_uint<1> )s_reg_37_slice.read()), 
                    (sc_bv<9>)((sc_uint<9> )s_reg_38.read())) ));
    break;
  case 1ULL: 
    from_tb_b_in1 = SobelFilter_Add2iLLu9_4_18_out1.read();
    break;
  case 2ULL: 
    from_tb_b_in1 = SobelFilter_Add3u9u2Cati0u2_4_21_out1.read();
    break;
  case 3ULL: 
    from_tb_b_in1 = SobelFilter_gen000001_4_43_out1.read();
    break;
  case 4ULL: 
    from_tb_b_in1 = (sc_uint<11> ) ((sc_uint<9> )s_reg_38.read());
    break;
  case 5ULL: 
    from_tb_b_in1 = SobelFilter_Add2iLLu9_4_53_out1.read();
    break;
  case 6ULL: 
    from_tb_b_in1 = SobelFilter_gen000001_4_49_out1.read();
    break;
  }
}
// resource: mux_8bx3i1c
void SobelFilter::drive_from_tb_b_DIN(){
  switch( (sc_uint<2>)(gs_ctrl1.read()) ) {
  default:
    from_tb_b_DIN = (sc_uint<8> ) (i_rgb_data.read().range(23,16));
    break;
  case 1ULL: 
    from_tb_b_DIN = from_tb_b_out1.read();
    break;
  case 2ULL: 
    from_tb_b_DIN = 0ULL;
    break;
  }
}
// resource: mux_1bx2i2c
void SobelFilter::drive_from_tb_b_CE(){
  if ( stall0.read() ) {
    from_tb_b_CE = 0ULL;
  } else {
    switch( (sc_uint<2>)(gs_ctrl10.read()) ) {
    default:
      from_tb_b_CE = 0ULL;
      break;
    case 1ULL: 
      from_tb_b_CE = 1ULL;
      break;
    case 2ULL: 
      if ( SobelFilter_LtiLLs11_4_42_out1.read() ) {
        from_tb_b_CE = 0ULL;
      } else {
        from_tb_b_CE = 1ULL;
      }
      break;
    case 3ULL: 
      if ( SobelFilter_LtiLLs11_4_56_out1.read() ) {
        from_tb_b_CE = 1ULL;
      } else {
        from_tb_b_CE = 0ULL;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
void SobelFilter::drive_from_tb_b_RW(){
  if ( stall0.read() ) {
    from_tb_b_RW = 0ULL;
  } else {
    if ( gs_ctrl3.read() ) {
      from_tb_b_RW = 1ULL;
    } else {
      from_tb_b_RW = 0ULL;
    }
  }
}
// resource: SobelFilter_Lti2s3_4  instance: SobelFilter_Lti2s3_4_15
void SobelFilter::SobelFilter_Lti2s3_4_15(){
  SobelFilter_Lti2s3_4_15_out1 = (/*imp*/sc_uint<1>)((sc_int<3> )s_reg_39.read()
                                  < (sc_int<3> )2LL);
}
// resource: SobelFilter_Add2iLLu9_4  instance: SobelFilter_Add2iLLu9_4_18
void SobelFilter::SobelFilter_Add2iLLu9_4_18(){
  SobelFilter_Add2iLLu9_4_18_out1 = ((sc_uint<9> )s_reg_38.read() + 1024ULL);
}
// resource: SobelFilter_LtiLLs11_4  instance: SobelFilter_LtiLLs11_4_20
void SobelFilter::SobelFilter_LtiLLs11_4_20(){
  SobelFilter_LtiLLs11_4_20_out1 = (/*imp*/sc_uint<1>)((sc_int<11> )s_reg_38
                                   .read() < (sc_int<11> )512LL);
}
// resource: mux_2bx3i1c
void SobelFilter::drive_SobelFilter_Add3u9u2Cati0u2_4_21_in3(){
  switch( (sc_uint<2>)(gs_ctrl12.read()) ) {
  default:
    SobelFilter_Add3u9u2Cati0u2_4_21_in3 = 0ULL;
    break;
  case 1ULL: 
    SobelFilter_Add3u9u2Cati0u2_4_21_in3 = s_reg_37_slice.read();
    break;
  case 2ULL: 
    if ( SobelFilter_Lti3u2_4_34_out1.read() ) {
      SobelFilter_Add3u9u2Cati0u2_4_21_in3 = s_reg_37_slice.read();
    } else {
      SobelFilter_Add3u9u2Cati0u2_4_21_in3 = (sc_uint<2> )s_reg_39.read();
    }
    break;
  }
}
// resource: mux_2bx2i1c
void SobelFilter::drive_SobelFilter_Add3u9u2Cati0u2_4_21_in2(){
  switch( (sc_uint<2>)(gs_ctrl12.read()) ) {
  default:
    SobelFilter_Add3u9u2Cati0u2_4_21_in2 = 0ULL;
    break;
  case 1ULL: 
    SobelFilter_Add3u9u2Cati0u2_4_21_in2 = s_reg_40.read();
    break;
  case 2ULL: 
    if ( SobelFilter_Lti3u2_4_34_out1.read() ) {
      SobelFilter_Add3u9u2Cati0u2_4_21_in2 = s_reg_40.read();
    } else {
      SobelFilter_Add3u9u2Cati0u2_4_21_in2 = 0ULL;
    }
    break;
  }
}
// resource: mux_9bx3i1c
void SobelFilter::drive_SobelFilter_Add3u9u2Cati0u2_4_21_in1(){
  switch( (sc_uint<2>)(gs_ctrl14.read()) ) {
  default:
    SobelFilter_Add3u9u2Cati0u2_4_21_in1 = 0ULL;
    break;
  case 1ULL: 
    SobelFilter_Add3u9u2Cati0u2_4_21_in1 = (sc_uint<9> )s_reg_38.read();
    break;
  case 2ULL: 
    SobelFilter_Add3u9u2Cati0u2_4_21_in1 = (sc_uint<9> )s_reg_43.read();
    break;
  }
}
// resource: SobelFilter_Add3u9u2Cati0u2_4  instance: SobelFilter_Add3u9u2Cati0u2_4_21
void SobelFilter::SobelFilter_Add3u9u2Cati0u2_4_21(){
  SobelFilter_Add3u9u2Cati0u2_4_21_out1 = (( (sc_uint<11> )(sc_bv<11>)(
                                          (sc_bv<2>)(
                                          SobelFilter_Add3u9u2Cati0u2_4_21_in3
                                          .read()), 
                                          (sc_bv<9>)(0ULL)) ) + ( (
                                          SobelFilter_Add3u9u2Cati0u2_4_21_in2
                                          .read() + 
                                          SobelFilter_Add3u9u2Cati0u2_4_21_in1
                                          .read()) ));
}
// resource: mux_2bx3i1c
void SobelFilter::drive_SobelFilter_Add2u2Mul2i3u2_4_22_in2(){
  if ( gs_ctrl15.read() ) {
    if ( SobelFilter_Lti3u2_4_34_out1.read() ) {
      SobelFilter_Add2u2Mul2i3u2_4_22_in2 = s_reg_37_slice.read();
    } else {
      SobelFilter_Add2u2Mul2i3u2_4_22_in2 = (sc_uint<2> )s_reg_39.read();
    }
  } else {
    SobelFilter_Add2u2Mul2i3u2_4_22_in2 = 0ULL;
  }
}
// resource: mux_2bx2i1c
void SobelFilter::drive_SobelFilter_Add2u2Mul2i3u2_4_22_in1(){
  if ( gs_ctrl15.read() ) {
    if ( SobelFilter_Lti3u2_4_34_out1.read() ) {
      SobelFilter_Add2u2Mul2i3u2_4_22_in1 = s_reg_40.read();
    } else {
      SobelFilter_Add2u2Mul2i3u2_4_22_in1 = 0ULL;
    }
  } else {
    SobelFilter_Add2u2Mul2i3u2_4_22_in1 = 0ULL;
  }
}
// resource: SobelFilter_Add2u2Mul2i3u2_4  instance: SobelFilter_Add2u2Mul2i3u2_4_22
void SobelFilter::SobelFilter_Add2u2Mul2i3u2_4_22(){
  SobelFilter_Add2u2Mul2i3u2_4_22_out1 = (SobelFilter_Add2u2Mul2i3u2_4_22_in2
                                         .read() * 3ULL + 
                                         SobelFilter_Add2u2Mul2i3u2_4_22_in1
                                         .read());
}
void SobelFilter::drive_filter2_in1(){
  filter2_in1 = SobelFilter_Add2u2Mul2i3u2_4_22_out1.read();
}
// resource: SobelFilter_Add2i1u2_4  instance: SobelFilter_Add2i1u2_4_25
void SobelFilter::SobelFilter_Add2i1u2_4_25(){
  SobelFilter_Add2i1u2_4_25_out1 = (s_reg_37_slice.read() + 1ULL);
}
// resource: SobelFilter_Add2i1u2_4  instance: SobelFilter_Add2i1u2_4_26
void SobelFilter::SobelFilter_Add2i1u2_4_26(){
  SobelFilter_Add2i1u2_4_26_out1 = (s_reg_40.read() + 1ULL);
}
// resource: mux_8bx2i0c
void SobelFilter::drive_SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_in1(){
  if ( gs_ctrl17.read() ) {
    SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_in1 = s_reg_45
                                                                  .read();
  } else {
    SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_in1 = from_tb_b_out1
                                                                  .read();
  }
}
// resource: SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4  instance: SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28
void SobelFilter::drive_bits_001(){
  bits_001 = (( (s_reg_41.read() * 299ULL + s_reg_44.read() * 587ULL) ) + 
             SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_in1.read()
              * 144ULL);
}
// resource: SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4  instance: SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28
void SobelFilter::SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28(){
  SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_out1 = (sc_uint<16> ) 
                                                                 (bits_001
                                                                 .read().range(
                                                                 18,3));
}
// resource: SobelFilter_Div_8U_27_4  instance: SobelFilter_Div_8U_27_4_29
void SobelFilter::SobelFilter_Div_8U_27_4_29(){
  SobelFilter_Div_8U_27_4_29_out1 = ((sc_uint<7> )125ULL == 0 ? ((sc_uint<8> 
                                    ) -1) : (sc_uint<8> ) (SobelFilter_R18_3Add3Mul2i144u8Mul2iLLu8Mul2i299u8_4_28_out1
                                    .read() / (sc_uint<7> )125ULL));
}
// resource: mux_8bx3i0c
void SobelFilter::drive_SobelFilter_Add2Mul2s8u8s8_4_30_in3(){
  switch( (sc_uint<2>)(gs_ctrl18.read()) ) {
  default:
    SobelFilter_Add2Mul2s8u8s8_4_30_in3 = (sc_int<8> ) (o_result_r_data.read());
    break;
  case 1ULL: 
    SobelFilter_Add2Mul2s8u8s8_4_30_in3 = (sc_int<8> ) (o_result_g_data.read());
    break;
  case 2ULL: 
    SobelFilter_Add2Mul2s8u8s8_4_30_in3 = (sc_int<8> ) (o_result_b_data.read());
    break;
  }
}
// resource: SobelFilter_Add2Mul2s8u8s8_4  instance: SobelFilter_Add2Mul2s8u8s8_4_30
void SobelFilter::SobelFilter_Add2Mul2s8u8s8_4_30(){
  SobelFilter_Add2Mul2s8u8s8_4_30_out1 = (/*cliff*/sc_int<32>)(
                                         SobelFilter_Add2Mul2s8u8s8_4_30_in3
                                         .read() + 
                                         SobelFilter_Div_8U_27_4_29_out1.read()
                                          * (sc_int<8> )s_reg_42.read());
}
// resource: SobelFilter_Lti3u2_4  instance: SobelFilter_Lti3u2_4_34
void SobelFilter::SobelFilter_Lti3u2_4_34(){
  SobelFilter_Lti3u2_4_34_out1 = (/*imp*/sc_uint<1>)(s_reg_40.read() < (
                                 sc_uint<2> )3ULL);
}
// resource: SobelFilter_Lti3u2_4  instance: SobelFilter_Lti3u2_4_38
void SobelFilter::SobelFilter_Lti3u2_4_38(){
  SobelFilter_Lti3u2_4_38_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )s_reg_39
                                 .read() < (sc_uint<2> )3ULL);
}
// resource: SobelFilter_Add2n128s8_4  instance: SobelFilter_Add2n128s8_4_39
void SobelFilter::SobelFilter_Add2n128s8_4_39(){
  SobelFilter_Add2n128s8_4_39_out1 = (/*cliff*/sc_int<32>)((sc_int<8> )
                                     o_result_r_data.read() + -128LL);
}
// resource: SobelFilter_Add2n128s8_4  instance: SobelFilter_Add2n128s8_4_40
void SobelFilter::SobelFilter_Add2n128s8_4_40(){
  SobelFilter_Add2n128s8_4_40_out1 = (/*cliff*/sc_int<32>)((sc_int<8> )
                                     o_result_g_data.read() + -128LL);
}
// resource: SobelFilter_Add2n128s8_4  instance: SobelFilter_Add2n128s8_4_41
void SobelFilter::SobelFilter_Add2n128s8_4_41(){
  SobelFilter_Add2n128s8_4_41_out1 = (/*cliff*/sc_int<32>)((sc_int<8> )
                                     o_result_b_data.read() + -128LL);
}
// resource: SobelFilter_LtiLLs11_4  instance: SobelFilter_LtiLLs11_4_42
void SobelFilter::SobelFilter_LtiLLs11_4_42(){
  SobelFilter_LtiLLs11_4_42_out1 = (/*imp*/sc_uint<1>)((sc_int<11> )s_reg_43
                                   .read() < (sc_int<11> )512LL);
}
// resource: mux_9bx2i1c
void SobelFilter::drive_SobelFilter_gen000001_4_43_in1(){
  if ( gs_ctrl19.read() ) {
    SobelFilter_gen000001_4_43_in1 = (sc_uint<9> )s_reg_38.read();
  } else {
    SobelFilter_gen000001_4_43_in1 = 0ULL;
  }
}
// resource: SobelFilter_gen000001_4  instance: SobelFilter_gen000001_4_43
void SobelFilter::SobelFilter_gen000001_4_43(){
  SobelFilter_gen000001_4_43_out1 = (SobelFilter_gen000001_4_43_in1.read() + 
                                    512ULL);
}
// resource: SobelFilter_Add2iLLu9_4  instance: SobelFilter_Add2iLLu9_4_53
void SobelFilter::SobelFilter_Add2iLLu9_4_53(){
  SobelFilter_Add2iLLu9_4_53_out1 = ((sc_uint<9> )s_reg_38.read() + 1024ULL);
}
// resource: SobelFilter_gen000001_4  instance: SobelFilter_gen000001_4_49
void SobelFilter::SobelFilter_gen000001_4_49(){
  SobelFilter_gen000001_4_49_out1 = ((sc_uint<9> )s_reg_38.read() + 512ULL);
}
// resource: SobelFilter_LtiLLs11_4  instance: SobelFilter_LtiLLs11_4_56
void SobelFilter::SobelFilter_LtiLLs11_4_56(){
  SobelFilter_LtiLLs11_4_56_out1 = (/*imp*/sc_uint<1>)((sc_int<11> )s_reg_38
                                   .read() < (sc_int<11> )512LL);
}
// resource: regr_en_sc_5
void SobelFilter::drive_global_state(){
  if ( (i_rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      global_state = global_state_next.read();
      break;
    }
  }
}
// resource: mux_5bx5i4c
void SobelFilter::drive_global_state_next(){
  switch( (sc_uint<5>)(global_state.read()) ) {
  default:
    global_state_next = (global_state.read() + 1ULL);
    break;
  case 2ULL: 
    if ( SobelFilter_LtiLLs11_4_14_out1.read() ) {
      global_state_next = 1ULL;
    } else {
      if ( SobelFilter_Lti2s3_4_15_out1.read() ) {
        global_state_next = 1ULL;
      } else {
        global_state_next = (global_state.read() + 1ULL);
      }
    }
    break;
  case 4ULL: 
    if ( SobelFilter_LtiLLs11_4_20_out1.read() ) {
      global_state_next = 3ULL;
    } else {
      global_state_next = (global_state.read() + 1ULL);
    }
    break;
  case 9ULL: 
    if ( SobelFilter_Lti3u2_4_34_out1.read() ) {
      global_state_next = 5ULL;
    } else {
      if ( SobelFilter_Lti3u2_4_38_out1.read() ) {
        global_state_next = 5ULL;
      } else {
        global_state_next = (global_state.read() + 1ULL);
      }
    }
    break;
  case 15ULL: 
    if ( SobelFilter_LtiLLs11_4_42_out1.read() ) {
      global_state_next = 5ULL;
    } else {
      global_state_next = (global_state.read() + 1ULL);
    }
    break;
  case 20ULL: 
    if ( SobelFilter_LtiLLs11_4_56_out1.read() ) {
      global_state_next = 16ULL;
    } else {
      global_state_next = 3ULL;
    }
    break;
  }
}
// resource: mux_3bx8i8c
// resource: regr_en_sc_3
void SobelFilter::drive_gs_ctrl0(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl0 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl0 = 0ULL;
        break;
      case 3ULL: 
        gs_ctrl0 = 1ULL;
        break;
      case 4ULL: case 9ULL: 
        gs_ctrl0 = 2ULL;
        break;
      case 15ULL: 
        gs_ctrl0 = 3ULL;
        break;
      case 16ULL: 
        gs_ctrl0 = 4ULL;
        break;
      case 17ULL: case 19ULL: 
        gs_ctrl0 = 5ULL;
        break;
      case 18ULL: 
        gs_ctrl0 = 6ULL;
        break;
      case 20ULL: 
        gs_ctrl0 = 7ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_2bx3i3c
// resource: regr_en_sc_2
void SobelFilter::drive_gs_ctrl1(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl1 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl1 = 0ULL;
        break;
      case 16ULL: case 18ULL: 
        gs_ctrl1 = 1ULL;
        break;
      case 19ULL: 
        gs_ctrl1 = 2ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_3bx5i5c
// resource: regr_en_sc_3
void SobelFilter::drive_gs_ctrl2(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl2 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl2 = 0ULL;
        break;
      case 1ULL: case 3ULL: case 15ULL: case 16ULL: case 17ULL: case 18ULL: 
      case 19ULL: 
        gs_ctrl2 = 1ULL;
        break;
      case 4ULL: 
        gs_ctrl2 = 2ULL;
        break;
      case 9ULL: 
        gs_ctrl2 = 3ULL;
        break;
      case 20ULL: 
        gs_ctrl2 = 4ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void SobelFilter::drive_gs_ctrl3(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl3 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl3 = 0ULL;
        break;
      case 1ULL: case 3ULL: case 16ULL: case 18ULL: case 19ULL: 
        gs_ctrl3 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_3bx7i7c
// resource: regr_en_sc_3
void SobelFilter::drive_gs_ctrl4(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl4 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl4 = 0ULL;
        break;
      case 3ULL: 
        gs_ctrl4 = 1ULL;
        break;
      case 5ULL: 
        gs_ctrl4 = 2ULL;
        break;
      case 15ULL: case 20ULL: 
        gs_ctrl4 = 3ULL;
        break;
      case 16ULL: 
        gs_ctrl4 = 4ULL;
        break;
      case 17ULL: case 19ULL: 
        gs_ctrl4 = 5ULL;
        break;
      case 18ULL: 
        gs_ctrl4 = 6ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_2bx4i4c
// resource: regr_en_sc_2
void SobelFilter::drive_gs_ctrl6(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl6 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl6 = 0ULL;
        break;
      case 1ULL: case 3ULL: case 5ULL: case 16ULL: case 17ULL: case 18ULL: case 
      19ULL: 
        gs_ctrl6 = 1ULL;
        break;
      case 15ULL: 
        gs_ctrl6 = 2ULL;
        break;
      case 20ULL: 
        gs_ctrl6 = 3ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_3bx7i7c
// resource: regr_en_sc_3
void SobelFilter::drive_gs_ctrl8(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl8 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl8 = 0ULL;
        break;
      case 3ULL: 
        gs_ctrl8 = 1ULL;
        break;
      case 6ULL: 
        gs_ctrl8 = 2ULL;
        break;
      case 15ULL: case 20ULL: 
        gs_ctrl8 = 3ULL;
        break;
      case 16ULL: 
        gs_ctrl8 = 4ULL;
        break;
      case 17ULL: case 19ULL: 
        gs_ctrl8 = 5ULL;
        break;
      case 18ULL: 
        gs_ctrl8 = 6ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_2bx4i4c
// resource: regr_en_sc_2
void SobelFilter::drive_gs_ctrl10(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl10 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl10 = 0ULL;
        break;
      case 1ULL: case 3ULL: case 6ULL: case 16ULL: case 17ULL: case 18ULL: case 
      19ULL: 
        gs_ctrl10 = 1ULL;
        break;
      case 15ULL: 
        gs_ctrl10 = 2ULL;
        break;
      case 20ULL: 
        gs_ctrl10 = 3ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_2bx3i3c
// resource: regr_en_sc_2
void SobelFilter::drive_gs_ctrl12(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl12 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl12 = 0ULL;
        break;
      case 5ULL: case 6ULL: 
        gs_ctrl12 = 1ULL;
        break;
      case 9ULL: 
        gs_ctrl12 = 2ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_2bx3i3c
// resource: regr_en_sc_2
void SobelFilter::drive_gs_ctrl14(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl14 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl14 = 0ULL;
        break;
      case 5ULL: case 6ULL: case 9ULL: 
        gs_ctrl14 = 1ULL;
        break;
      case 15ULL: 
        gs_ctrl14 = 2ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void SobelFilter::drive_gs_ctrl15(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl15 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl15 = 0ULL;
        break;
      case 9ULL: 
        gs_ctrl15 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void SobelFilter::drive_gs_ctrl17(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl17 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl17 = 0ULL;
        break;
      case 8ULL: case 9ULL: 
        gs_ctrl17 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_2bx3i3c
// resource: regr_en_sc_2
void SobelFilter::drive_gs_ctrl18(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl18 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl18 = 0ULL;
        break;
      case 8ULL: 
        gs_ctrl18 = 1ULL;
        break;
      case 9ULL: 
        gs_ctrl18 = 2ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void SobelFilter::drive_gs_ctrl19(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl19 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<5>)(global_state_next.read()) ) {
      default:
        gs_ctrl19 = 0ULL;
        break;
      case 20ULL: 
        gs_ctrl19 = 1ULL;
        break;
      }
      break;
    }
  }
}
void SobelFilter::drive_i_rgb_busy(){
  i_rgb_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
               SobelFilter_gen_busy_r_4_61_out1.read().range(2,2)));
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_61
void SobelFilter::SobelFilter_gen_busy_r_4_61_p8(){
  SobelFilter_gen_busy_r_4_61_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)
                                     ((sc_bv<1>)(
                                     SobelFilter_gen_busy_r_4_61_gnew_req.read()
                                     ), 
                                     (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                     (sc_bv<1>)(SobelFilter_gen_busy_r_4_61_gdiv
                                     .read()), 
                                     (sc_bv<1>)(SobelFilter_gen_busy_r_4_61_gen_busy_i_rgb_m_data_is_invalid_next
                                     .read())) ))) ));
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_61
void SobelFilter::SobelFilter_gen_busy_r_4_61_p7(){
  SobelFilter_gen_busy_r_4_61_gen_busy_i_rgb_m_data_is_invalid_next = ~(sc_uint<1>)SobelFilter_gen_busy_r_4_61_gdiv
                                                                      .read();
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_61
void SobelFilter::SobelFilter_gen_busy_r_4_61_p6(){
  SobelFilter_gen_busy_r_4_61_gdiv = (sc_uint<1> ) (i_rgb_vld.read() & !
                                     SobelFilter_gen_busy_r_4_61_gnew_req.read()
                                     );
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_61
void SobelFilter::SobelFilter_gen_busy_r_4_61_p5(){
  SobelFilter_gen_busy_r_4_61_gnew_req = (sc_uint<1> ) (i_rgb_m_busy_req_0
                                         .read() & ( i_rgb_m_unvalidated_req
                                         .read() | (sc_uint<1> )i_rgb_vld.read()
                                          ));
}
// resource: regr_ss_1
void SobelFilter::drive_i_rgb_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_unvalidated_req = 1ULL;
  } else {
    i_rgb_m_unvalidated_req = (sc_uint<1> ) (SobelFilter_N_Muxb_1_2_23_4_10_out1
                              .read());
  }
}
// resource: SobelFilter_N_Muxb_1_2_23_4
void SobelFilter::SobelFilter_N_Muxb_1_2_23_4_10(){
  if ( i_rgb_m_busy_req_0.read() ) {
    SobelFilter_N_Muxb_1_2_23_4_10_out1 = (sc_uint<1> ) (i_rgb_m_unvalidated_req
                                          .read());
  } else {
    SobelFilter_N_Muxb_1_2_23_4_10_out1 = (sc_uint<1> ) (i_rgb_vld.read());
  }
}
void SobelFilter::drive_o_result_r_vld(){
  o_result_r_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_2_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_2
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_2(){
  SobelFilter_Or_1Ux1U_1U_4_2_out1 = (sc_uint<1> ) (o_result_r_m_unacked_req
                                     .read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_1_1_out1.read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_r_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_r_m_unacked_req = 0ULL;
  } else {
    o_result_r_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_57_out1
                               .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_57
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_57(){
  SobelFilter_And_1Ux1U_1U_4_57_out1 = (sc_uint<1> ) (o_result_r_busy.read() & 
                                       o_result_r_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_1  instance: SobelFilter_Xor_1Ux1U_1U_1_1
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_1_1(){
  SobelFilter_Xor_1Ux1U_1U_1_1_out1 = (sc_uint<1> ) (o_result_r_m_req_m_trig_req
                                      .read() ^ o_result_r_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_r_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_r_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_r_m_req_m_prev_trig_req = o_result_r_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_1  instance: SobelFilter_Not_1U_1U_1_3
void SobelFilter::SobelFilter_Not_1U_1U_1_3(){
  SobelFilter_Not_1U_1U_1_3_out1 = !o_result_r_m_req_m_trig_req.read();
}
void SobelFilter::drive_o_result_g_vld(){
  o_result_g_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_5_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_5
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_5(){
  SobelFilter_Or_1Ux1U_1U_4_5_out1 = (sc_uint<1> ) (o_result_g_m_unacked_req
                                     .read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_1_4_out1.read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_g_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_g_m_unacked_req = 0ULL;
  } else {
    o_result_g_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_58_out1
                               .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_58
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_58(){
  SobelFilter_And_1Ux1U_1U_4_58_out1 = (sc_uint<1> ) (o_result_g_busy.read() & 
                                       o_result_g_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_1  instance: SobelFilter_Xor_1Ux1U_1U_1_4
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_1_4(){
  SobelFilter_Xor_1Ux1U_1U_1_4_out1 = (sc_uint<1> ) (o_result_g_m_req_m_trig_req
                                      .read() ^ o_result_g_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_g_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_g_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_g_m_req_m_prev_trig_req = o_result_g_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_1  instance: SobelFilter_Not_1U_1U_1_6
void SobelFilter::SobelFilter_Not_1U_1U_1_6(){
  SobelFilter_Not_1U_1U_1_6_out1 = !o_result_g_m_req_m_trig_req.read();
}
void SobelFilter::drive_o_result_b_vld(){
  o_result_b_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_8_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_8
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_8(){
  SobelFilter_Or_1Ux1U_1U_4_8_out1 = (sc_uint<1> ) (o_result_b_m_unacked_req
                                     .read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_1_7_out1.read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_b_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_b_m_unacked_req = 0ULL;
  } else {
    o_result_b_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_59_out1
                               .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_59
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_59(){
  SobelFilter_And_1Ux1U_1U_4_59_out1 = (sc_uint<1> ) (o_result_b_busy.read() & 
                                       o_result_b_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_1  instance: SobelFilter_Xor_1Ux1U_1U_1_7
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_1_7(){
  SobelFilter_Xor_1Ux1U_1U_1_7_out1 = (sc_uint<1> ) (o_result_b_m_req_m_trig_req
                                      .read() ^ o_result_b_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_b_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_b_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_b_m_req_m_prev_trig_req = o_result_b_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_1  instance: SobelFilter_Not_1U_1U_1_9
void SobelFilter::SobelFilter_Not_1U_1U_1_9(){
  SobelFilter_Not_1U_1U_1_9_out1 = !o_result_b_m_req_m_trig_req.read();
}
