`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  2 2021 00:55:04 CST (May  1 2021 16:55:04 UTC)

module ColorTransform_Add_2U_16_4(in1, out1);
  input [1:0] in1;
  output [1:0] out1;
  wire [1:0] in1;
  wire [1:0] out1;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
endmodule

